uses: actions/checkout@v3
- name: Terraform Init
id: init
run: cd ~/SRE-TF/lab-21-EC2-Instance && terraform init
- name: Terraform Validate
id: validate
run: cd ~/SRE-TF/lab-21-EC2-Instance && terraform validate -no-color
- name: Terraform Plan
id: plan
if: github.event_name == 'pull_request'
run: cd ~/SRE-TF/lab-21-EC2-Instance && terraform plan -no-color -
input=false
continue-on-error: true
- uses: actions/github-script@v6
if: github.event_name == 'pull_request'
Deploying EC2 Instance – Lab Guide 5
env:
PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
with:
github-token: ${{ secrets.GITHUB_TOKEN }}
script: |
const output = `#### Terraform Format and Style 
